### ISSUE TITLE
Line endings with \r\n seems to be unhandled

### ISSUE THREAD

**Issue by zerodeux** [xavierleroy/spamoracle#2]
Hello,

after a long debug session I realized why "spamoracle mark" would refuse to add a X-Spam header to its output while it reported no error and exited with 0 status : its input had EOL consisting of \r\n (which is actually RFC-compliant), and I fixed the problem by pre-filtering the input (\r\n -> \n).

I have a pretty common Postfix+Dovecot+Sieve setup, other users might be impacted.

I think it's important to accept andparse \r\n EOL, this should be fixed.

I also think it may be safer if spamoracle exited with non-0 status if it could not "mark" the output, because it would clearly indicate that the requested command has failed. The documentation makes it clear that for all issues, the X-Spam header is added : I had to thorougly read the wole doc to check if there was not a special condition where marking woult not occur - and yes anyway I should read the whole doc, and it's short and well edited.

To help with people running in similar issues, it would be usefull if spamoracle would report something on stderr as why it refused to "mark" the output. Note that in my case I suppose spamoracle parsed the input as a single header, and I guess it would have output an error like "no body found" and I would have been still quite baffled. Still it would narrow down the problem, I spent lots of time debugging Sieve (which has a very bad doc).

And thanks for your software !

**Comment by xavierleroy** [comment]
You are correct that \r\n end-of-lines confuse SpamOracle, especially the part that looks for \n\n to separate headers from body!

I agree about printing a message on stderr if marking fails.  I prefer to leave the message as-is and exit normally rather than exit with nonzero status, because there is a risk of losing the mail entirely in the latter case.  In other words, an unmarked e-mail is better than a possibly lost e-mail.

I'll push a fix soon.

**Comment by zerodeux** [comment]
Thanks !
